# Generated by Django 3.1.2 on 2020-10-25 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('chainlink', 'Chainlink'), ('litecoin', 'Litecoin'), ('pokadot', 'Pokadot'), ('yearnfinance', 'YearnFinance')], default='bitcoin', max_length=12)),
                ('month_bought_at', models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('July', 'July'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=4)),
                ('amount_bought', models.PositiveIntegerField()),
                ('price_bought_at', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_transactions', to=settings.AUTH_USER_MODEL)),
                ('subaccountowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subaccount.subaccount')),
            ],
        ),
    ]
