# Generated by Django 3.1.2 on 2020-10-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subaccount', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='subaccount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='subaccountid', to='subaccount.subaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_bought_at',
            field=models.PositiveIntegerField(),
        ),
    ]
