# Generated by Django 3.1.2 on 2020-10-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20201023_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='ownerID',
            new_name='owner',
        ),
    ]
