# Generated by Django 3.1.2 on 2020-10-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subaccount', '0002_auto_20201023_1436'),
        ('transaction', '0006_auto_20201023_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subaccountowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transations', to='subaccount.subaccount'),
        ),
    ]
