# Generated by Django 3.1.2 on 2020-10-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20201023_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_bought_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
