# Generated by Django 3.1.2 on 2020-10-23 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_auto_20201023_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_bought_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
